# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17uiUf7mo_FtUDzj3sPZ8PxI5H7_oDcqd
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

cricket = pd.read_csv('cricket.csv')
df = cricket[['SR','Ave']]

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)
#convet df_scaled series into Dataframe
df_scaled = pd.DataFrame(df_scaled)
#Assign column names
df_scaled.columns = ['SR', 'Ave']

kmeans = KMeans(n_clusters = 4, max_iter = 50, random_state = 100)
kmeans.fit(df_scaled)

cricket['cluster_id'] = kmeans.labels_

clustering =cricket[["id","cluster_id"]]

clustering.to_csv("clustering.csv",index=False)

